### PR TITLE
Remove spaces automatically

### PR DESCRIPTION
**Pull request by tnfAngel**

### CODE REVIEW

**Comment by dev-737** [comment]
Any idea why the check is failing?

**Comment by tnfAngel** [comment]
> Any idea why the check is failing?

trying to push on a branch that does not exists on the original repo (remove-spaces), when the pr is merged, it will work, but i will fix the CI asap

**Review by dev-737 — APPROVED** [review]
> > Any idea why the check is failing?
> 
> trying to push on a branch that does not exists on the original repo (remove-spaces), when the pr is merged, it will work, but i will fix the CI asap

Alright, the rest looks good!

**Comment by dev-737** [comment]
Create another pr for the CI fix, I'll merge this one

**Pull request merged**
